### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by Bismaon** [Bismaon/Jeu_De_Carte#2]
- [x] compile better
- [x] have an entry to input the username
- [x] have the first card of the dealer on the table before the player draws anything
- [x] Create button on the side, indicating the amount the player is betting
    - [x] white = $1
    - [x] red = $5
    - [x] green = $25
    - [x] orange = $50
    - [x] black = $100
    - [x] purple = $500

**Comment by Bismaon** [comment]
* have an entry to input the username
